### PR TITLE
[Ready] Changes centering calculations for modals

### LINKED ISSUE #7: Centering causes blurriness on odd-pixel widths.
We could center using the old method and round out to the nearest pixel, but we stopped using that because of responsiveness. Someone said something about flexbox.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37993451-centering-causes-blurriness-on-odd-pixel-widths?utm_campaign=plugin&utm_content=tracker%2F6741324&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F6741324&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by p-shannon**
Fixes #7 and https://github.com/elementary/website/issues/1255

I don't know how to test this so please tell me how to do so, or test it yourself and confirm the proposed changes are sufficient. Thank you!

### CODE REVIEW

**Comment by lewisgoddard** [comment]
To test you should be able to just open the index.html file in the repository and click any modal button there.

I think we're going to have to expressly include a container though, styling the modals normal parent will probably break some other styling. It's probably best if we have a container that is explicitly set as 100% width and 100% height to center in.

**Comment by p-shannon** [comment]
Alright, tested it and everything and it's good. Let me know if anything else needs doing (differently).

**Comment by lewisgoddard** [comment]
I'm closing this in favour of #13 where I've done basically the same thing by moving the existing overlay around and using that for positioning instead of creating a whole new element. Thanks for the help!

**Comment by p-shannon** [comment]
No problem. I actually tried to move it to the existing overlay, but I couldn't figure out how to resolve the resulting opacity issue. I'll look at your implementation to see how it was done.

**Comment by lewisgoddard** [comment]
I passed the opacity into an `rgba` background so that it wouldn't affect children like an actual `opacity` style would.

**Comment by p-shannon** [comment]
Yep, just saw the code now. I thought about that, but then I realized I'd have to figure out how exactly you handled the fade out. I also see you refactored the relevant bits  significantly, even changing the overlay from a class to an ID, which isn't something I could have done.

**Comment by lewisgoddard** [comment]
Yeah, I ended up just breaking the fadeOut in favor of CSS Transitions. jQuery was getting some pretty poor framerates over on elementary.

**Pull request closed without merging**
