### PR TITLE
href fix browser naviagtion

### PR DESCRIPTION
**Pull request by charanrajtc**
some times browsers add '/' character in the begining of the href attr

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Can you name a browser I can test in that that HREF fix affects?

**Comment by charanrajtc** [comment]
I made short video of repeating the error the password is "n1ghth4wk" 

https://vimeo.com/154424202

**Comment by lewisgoddard** [comment]
I understand now, this is not a browser quirk, you are lacking a class on that site. elementary.io include a snippet of code that adds the pathname to every href that isn't a modal trigger. Because you didn't include the `.open-modal` class (not meant to be a unique, IDs are unique) their site modified it. This isn't a problem with leanModal2, and adding that class there will solve your problem. Remember, if you are targeting one specific thing, us an `#id`.

```
    setTimeout(function () {
        $('a[href^="#"]').each(function () {
            if ( !$(this).hasClass('open-modal') ) {
                var href = $(this).attr('href');
                $(this).attr('href', window.location.pathname + href);
            }
        });
    }, 0);
```

**Comment by charanrajtc** [comment]
Hmm ok

**Pull request closed without merging**
